apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    k8s-app: ibmce-cpd-install
resources:
  - service-account.yaml
  - rolebindings.yaml
  - secret.yaml
  - storage.yaml
  - case-00.yaml
  - case-01.yaml
  - case-02.yaml
  - case-03.yaml
  - case-04.yaml
  - case-05.yaml
  - case-06.yaml
  - case-07.yaml
  - case-08.yaml
  - case-09.yaml
  - case-10.yaml
  - configmap.yaml
  - pod.yaml

